name: CI/CD GHCR LAMP Docker

on:
  push:
    branches: [ "ghcr" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Pull des containers
        run: docker compose -f docker-compose-GHCR.yml pull

      - name: Test local du container
        run: |
          docker compose -f docker-compose-GHCR.yml up -d
          sleep 20
          curl -f http://localhost:8080 || exit 1
          docker compose -f docker-compose-GHCR.yml down

    deploy:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Récupération du code
          uses: actions/checkout@v4

        - name: Config SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        - name: Déploiement sur le VPS
          run: |
            rsync -avz -e "ssh -p $PORT" --exclude '.git'  --exclude '.github' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/lamp-app
            ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/lamp-app && docker compose -f docker-compose-GHCR.yml pull && docker compose -f docker-compose-GHCR.yml up -d"
