name: CI/CD deploy LAMP Docker on VPS server

on:
  push:
    branches: [ "/part1-githubactions" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Build des containers
        run: docker compose -f docker-compose.yml build

      - name: Test local du container
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 15
          curl -f http://localhost:8080 || exit 1
          docker compose down

    deploy:
      runs-on: ubuntu-latest
      needs: build
      if: github.ref == 'refs/heads/main'

      steps:
        - name: Récupération du code
          uses: actions/checkout@v4

        - name: Config SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -p ${{ secrets.VPS_PORT }} -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

        - name: Test SSH connexion
          run: ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "ls -la ~/"

        - name: Déploiement sur le VPS
          run: |
            rsync -avz -e "ssh -p ${{ secrets.VPS_PORT }}" --exclude '.git'  --exclude '.github' ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:~/lamp-app
            ssh -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd ~/lamp-app && docker compose pull && docker compose up -d --build"
