name: Build & Push Docker to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run:  echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Lowercase owner
        run: |
          OWNER_LC="${{ github.repository_owner,, }}"
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV

      - name: Build image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/lamp-app:latest ./lamp

      - name: Push image
        run: docker push ghcr.io/${{ github.repository_owner }}/lamp-app:latest
